### ISSUE TITLE
Errors on mac

### ISSUE THREAD

**Issue by n-029894** [basilioss/mdt#2]
The List, Add, and Edit menu options all fail with the same error: 

```
ls: todo.md 
: No such file or directory 
Error: No todo files found. 
``` 

This happens regardless if I am using `-d` or `-i`. 

Additionally, I can add one item to the inbox but I am not able to add any additional items. The error for this is: 

``` 
sed: 1: "todo.md": undefined label 'odo.md' 
``` 

gum version 0.9.0 
OSX Monterrey 
zsh version 5.8.1

**Comment by basilioss** [comment]
macOS uses FreeBSD's tools that have some limitations. The easiest way to fix these errors is to install the GNU version of these utilities with homebrew (https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities) and add `/usr/local/opt/coreutils/libexec/gnubin` before other directories in your PATH. If that doesn't work, check out [this](https://gist.github.com/skyzyx/3438280b18e4f7c490db8a2a2ca0b9da) article that adds a little more stuff to your PATH. As far as I understand, you only need to install `coreutils`, `findutils`, `gnu-sed` and `grep`.
