### ISSUE TITLE
Feature Request: Add Multiple Items at Once

### ISSUE THREAD

**Issue by datsfilipe** [basilioss/mdt#3]
Currently, if I want to add three items to my list, I have to type `mdt`, press `enter`, go to add option, press `enter` when done, and then repeat the process two more times. This can be quite tedious, especially if I have a lot of items to add.

Is it possible to implement a feature that allows users to add multiple items at once? For example, perhaps we could use `ctrl + enter` to add more items to the list without having to go through the process of typing `mdt` and going to add option each time.

***Note: great tool!***

**Comment by basilioss** [comment]
It's possible to continuously add items until a user presses Ctrl+C or Esc, but currently I'm not sure if that's the best way to implement it and if it's even necessary. You can just open a file in a text editor to batch create tasks. If you use vim, there's [vimwiki](https://github.com/vimwiki/vimwiki) plugin to simplify the creation of checkboxes or you can quickly insert them in any text editor with [espanso](https://espanso.org) for example.

**Comment by datsfilipe** [comment]
> It's possible to continuously add items until a user presses Ctrl+C or Esc, but currently I'm not sure if that's the best way to implement it and if it's even necessary.

Maybe this is fine if an option in the config enables this? so that the user can edit his preferences.

> You can just open a file in a text editor

What I like about the tool is the ability to manage the list quickly, I think it kind of breaks this mode of use as it becomes a slower task than could be.

*Note: Those are mostly my thoughts on how I'd like it to work, if in general you don't think it's necessary to implement that's fine.*
